### ISSUE TITLE
Release checklist v0.14

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#1324]
## Shiny

- [x] Final test pass
- [x] NEWS is up to date
- [x] Fix NEWS URLs (use https and point to shiny.rstudio.com)
- [x] LICENSE is up to date
- [x] Version bump
- [x] R CMD check --as-cran
- [x] Reverse dependency check
- [x] Submit to CRAN
- [x] When accepted on CRAN, tag commit with version, push tag

## shiny.rstudio.com

- [x] Make sure all articles are added in staging
- [x] Run staticdocs
- [x] Move previous /reference/latest to /reference/vX.Y.Z
- [x] Upgrade notes
- [x] Merge staging into master and push
- [x] Redeploy gallery.shinyapps.io

## Communication

- [x] Write announcement
- [x] Publish blog post
- [x] Send announcement email to shiny-discuss
- [x] Tweet

**Comment by jcheng5** [comment]
Future checklists will need to make sure they test old a new ggplot2 versions (<=2.1 and >=2.2)

**Comment by bborgesr** [comment]
@jcheng5 can you briefly explain why?

**Comment by wch** [comment]
It's because I updated the plot interaction code to work with ggplot2 >2.1.0.
