### ISSUE TITLE
Release checklist 0.14.1

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#1401]
## Shiny

- [x] Final test pass
- [x] Test with ggplot2 2.1.0 and 2.1.0.9000
- [x] NEWS is up to date
- [x] Fix NEWS URLs (use https and point to shiny.rstudio.com)
- [x] LICENSE is up to date
- [x] Version bump
- [x] Run Grunt (so that shiny.js.min gets updated version number)
- [x] R CMD check --as-cran
- [x] Reverse dependency check
- [x] Submit to CRAN
- [x] When accepted on CRAN, tag commit with version, push tag

## shiny.rstudio.com

- [x] Make sure all articles are added in staging
- [x] Run staticdocs
- [x] Move previous /reference/latest to /reference/vX.Y.Z
- [x] Upgrade notes
- [x] Merge staging into master and push
- [ ] Redeploy gallery.shinyapps.io

## Communication

- [ ] Write announcement
- [ ] Publish blog post
- [ ] Send announcement email to shiny-discuss
- [ ] Tweet
