### ISSUE TITLE
Release checklist 1.0

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#1522]
## Shiny
- [x] Final test pass
- [x] Test with ggplot2 2.1.0 and 2.2, 2.2.1
- [x] NEWS is up to date
- [x] LICENSE is up to date
- [x] Version bump
- [x] Run Grunt (so that shiny.js.min gets updated version number)
- [x] R CMD check --as-cran
- [x] Reverse dependency check
- [ ] Email shiny-discuss
- [x] Submit to CRAN
- [x] When accepted on CRAN, tag commit with version, push tag
- [ ] Draft blog post
- [ ] Publish blog post
## shiny.rstudio.com
- [x] Make sure all articles are added in staging
- [x] Run staticdocs
- [x] Move previous /reference/latest to /reference/vX.Y.Z
- [x] Upgrade notes
- [x] Merge staging into master and push
- [x] Redeploy gallery.shinyapps.io

**Comment by daattali** [comment]
It looks like shiny 1.0 is released on CRAN, but on GitHub shiny is still at 0.14.x - not sure if that's on purpose
