### ISSUE TITLE
Release Checklist 1.0.1

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#1622]
## Shiny
- [x] Final test pass 
     - [x] **Joe**: IE 9 - Shiny Server Pro
     - [x] **Joe**: IE 11 - ShinyApps.io
     - [x] **Winston**: Firefox - RSConnect
     - [x] **Winston**: Chrome - Shiny Server
     - [x] **Barbara**: Edge - ShinyApps.io
     - [x] **Barbara**: Safari - Shiny Server Pro
- [x] Test with ggplot2 2.1.0 and 2.2, 2.2.1
- [x] NEWS is up to date
- [x] LICENSE is up to date
- [x] Version bump
- [x] Run Grunt (so that shiny.js.min gets updated version number)
- [x] R CMD check --as-cran
- [x] Reverse dependency check
- [x] Email shiny-discuss
- [x] Submit to CRAN
- [x] When accepted on CRAN, tag commit with version, push tag
- [x] Draft blog post <details><summary>we could use what we have at the top if the NEWS.md file</summary>
This is a maintenance release of Shiny, mostly aimed at fixing bugs and introducing minor features. The most notable additions in this version of Shiny are the introduction of the `reactiveVal()` function (it's like `reactiveValues()`, but it only stores a single value), and that the choices of `radioButtons()` and `checkboxGroupInput()` can now contain HTML content instead of just plain text.
</details>

- [x] Publish blog post
## shiny.rstudio.com
- [x] Make sure all articles are added in staging
- [x] Update JS events article for new input fields
- [x] Run staticdocs
- [x] Move previous /reference/latest to /reference/vX.Y.Z
- [x] Upgrade notes
- [x] Merge staging into master and push: https://github.com/rstudio/shiny-dev-center/pull/38
- [x] Redeploy gallery.shinyapps.io

**Comment by wch** [comment]
When submitting to CRAN, we'll have to mention this NOTE, and explain that those functions are in  the upcoming version of ggplot2, and that shiny will detect when there's a previous version of ggplot2 and use a different code path in that case:

```
checking dependencies in R code ... NOTE
Missing or unexported objects:
  ‘ggplot2::summarise_coord’ ‘ggplot2::summarise_layers’
  ‘ggplot2::summarise_layout’
```

**Comment by bborgesr** [comment]
Let's also remember to push Sean's usage tracking article to shiny-dev-center master

**Comment by bborgesr** [comment]
revdep was mostly ok (the errors didn't seem related to Shiny at all), thanks to Winston for the help with this saga!

**Comment by bborgesr** [comment]
Here's the results of:

<details>
<summary>devtools::check(args="--as-cran") (just the two notes we already knew about)</summary>

```r
==> devtools::check(args = c('--as-cran','--no-manual','--run-donttest'))

Updating shiny documentation
Loading shiny
Setting env vars --------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building shiny ----------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' CMD build '/Users/barbaraborges/shiny' --no-resave-data --no-manual
* checking for file ‘/Users/barbaraborges/shiny/DESCRIPTION’ ... OK
* preparing ‘shiny’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘shiny_1.0.1.tar.gz’
'/Library/Frameworks/R.framework/Resources/bin/R' CMD check '/var/folders/6b/xmhjngk91hd6d61027q69kz40000gn/T//RtmpG8ImqF/shiny_1.0.1.tar.gz' --as-cran --timings --as-cran --no-manual --run-donttest --no-manual
Setting env vars --------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking shiny ----------------------------------------------------------------
* using log directory ‘/Users/barbaraborges/shiny.Rcheck’
* using R version 3.3.3 (2017-03-06)
* using platform: x86_64-apple-darwin13.4.0 (64-bit)
* using session charset: UTF-8
* using options ‘--run-donttest --no-manual --as-cran’
* checking for file ‘shiny/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘shiny’ version ‘1.0.1’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘shiny’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is  7.4Mb
  sub-directories of 1Mb or more:
    www   6.2Mb
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... NOTE
Missing or unexported objects:
  ‘ggplot2::summarise_coord’ ‘ggplot2::summarise_layers’
  ‘ggplot2::summarise_layout’
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
 OK
* DONE
Status: 2 NOTEs
checking installed package size ... NOTE
  installed size is  7.4Mb
  sub-directories of 1Mb or more:
    www   6.2Mb

checking dependencies in R code ... NOTE
Missing or unexported objects:
  ‘ggplot2::summarise_coord’ ‘ggplot2::summarise_layers’
  ‘ggplot2::summarise_layout’
R CMD check results
0 errors | 0 warnings | 2 notes

R CMD check succeeded
```
</details>

<details>
<summary>and the session_info()</summary>

```r
> devtools::session_info()
Session info ----------------------------------------------------------------
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.1.127)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Lisbon               
 date     2017-03-29                  

Packages --------------------------------------------------------------------
 package   * version     date       source                          
 devtools    1.12.0.9000 2017-03-29 Github (hadley/devtools@d8ab190)
 digest      0.6.12      2017-01-27 cran (@0.6.12)                  
 htmltools   0.3.5       2016-03-21 CRAN (R 3.3.0)                  
 httpuv      1.3.3       2015-08-04 CRAN (R 3.3.0)                  
 memoise     1.0.0       2016-01-29 CRAN (R 3.3.0)                  
 mime        0.5         2016-07-07 CRAN (R 3.3.0)                  
 pkgbuild    0.0.0.9000  2017-03-29 Github (r-pkgs/pkgbuild@5ed87aa)
 pkgload     0.0.0.9000  2017-03-29 Github (r-pkgs/pkgload@3a96cf2) 
 R6          2.2.0       2016-10-05 CRAN (R 3.3.0)                  
 Rcpp        0.12.10     2017-03-19 cran (@0.12.10)                 
 shiny     * 1.0.1       2017-03-29 local                           
 withr       1.0.2       2016-06-20 CRAN (R 3.3.0)                  
 xtable      1.8-2       2016-02-05 CRAN (R 3.3.0)                  
 yaml        2.1.14      2016-11-12 CRAN (R 3.3.2)   
```

</details>
