### ISSUE TITLE
Shiny 1.0.2 hotfix release checklist 

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#1666]
## Shiny
- [x] Final test pass 
     - [x] **Barbara**: any browser; gallery.shinyapps.io; 001-040
     - [x] **Joe**: any browser; gallery.shinyapps.io; 040-080
     - [x] **Winston**: any browser; gallery.shinyapps.io; 080-120
- [x] Test with ggplot2 2.1.0 and 2.2, 2.2.1
- [x] NEWS is up to date
- [x] LICENSE is up to date
- [x] Version bump
- [x] Run Grunt (so that shiny.js.min gets updated version number)
- [x] R CMD check --as-cran
- [ ] Reverse dependency check
- [x] Reply to [this shiny-discuss post](https://groups.google.com/forum/#!msg/shiny-discuss/BL7DxPb7_6s/3FJkjFPeAwAJ;context-place=searchin/shiny-discuss/1.0.1%7Csort:relevance) (the 1.0.1 announcement).
- [x] Submit to CRAN
- [x] When accepted on CRAN, tag commit with version, push tag
- [x] Draft blog post about switching MathJax CDN across the board<details><summary>we could use some of what we have at the top of the NEWS.md file</summary>
This is a hotfix release of Shiny. The primary reason for this release is because the web host for MathJax JavaScript library is scheduled to be shut down in the next few weeks. After it is shut down, Shiny applications that use MathJax will no longer be able to load the MathJax library if they are run with Shiny 1.0.1 and below. (If you don't know whether your application uses MathJax, it probably does not.) For more information about why the MathJax CDN is shutting down, see https://www.mathjax.org/cdn-shutting-down/.
</details>

- [ ] Publish blog post

## shiny.rstudio.com
- [x] Make sure all articles are added in staging
- [x] Run staticdocs
- [x] Move previous /reference/latest to /reference/X.Y.Z
- [x] Upgrade notes
- [x] Merge changes into staging and push: https://github.com/rstudio/shiny-dev-center/pull/41
- [x] Merge staging into master and push: https://github.com/rstudio/shiny-dev-center/pull/42
- [x] Redeploy gallery.shinyapps.io

**Comment by bborgesr** [comment]
When testing in shinyapps.io, it's nice to have a list of all the apps, so we can change the URL quickly. I made this list and thought I'd share it here in case you also find it useful. (The indented apps are the `0xx-widget-*` that we agreed we don't need to test, if we test `081-widgets-gallery`).

<details><summary>All Shiny example apps</summary>

- 001-hello
- 002-text
- 003-reactivity
- 004-mpg
- 005-sliders
- 006-tabsets
- 007-widgets
- 008-html
- 009-upload
- 010-download
- 011-timer
- 012-datatables
- 013-selectize
- 014-onflushed
- 015-layout-navbar
- 015-layout-sidebar
- 016-knitr-pdf
- 017-select-vs-selectize
- 018-datatable-options
- 019-mathjax
- 020-knit-html
- 021-selectize-plot
- 022-unicode-chinese
- 023-optgroup-server
- 024-optgroup-selectize
- 025-loop-ui
- 026-shiny-inline
- 027-absolutely-positioned-panels
- 028-actionbutton-demo
- 030-basic-datatable
- 032-client-data-and-query-string
- 033-conditionalpanel-demo
- 034-current-time
- 035-custom-input-bindings
- 036-custom-input-control
- 037-date-and-date-range
- 039-download-file
- 040-dynamic-clustering
- 041-dynamic-ui
- 047-image-output
- 048-including-html-text-and-markdown-files
- 049-isolate-demo
- 050-kmeans-example
- 051-movie-explorer
- 052-navbar-example
- 053-navlistpanel-example
- 054-nvd3-line-chart-output
- 055-observer-demo
- 057-plot-plus-three-columns
- 059-reactive-poll-and-file-reader
- 060-retirement-simulation
- 061-server-to-client-custom-messages
- 062-submitbutton-demo
- 063-superzip-example
- 064-telephones-by-region
- 065-update-input-demo
- 066-upload-file
- 067-vertical-layout
    -  068-widget-action-button
    -  069-widget-check-group
    - 	070-widget-checkbox
    - 	071-widget-date
    - 	072-widget-date-range
    - 	073-widget-file
    - 	074-widget-numeric
    - 	075-widget-radio
    - 	076-widget-select
    - 	077-widget-slider
    - 	078-widget-slider-range
    - 	079-widget-submit
    - 	080-widget-text
- 081-widgets-gallery
- 082-word-cloud
- 083-front-page
- 084-single-file
- 085-progress
- 086-bus-dashboard
- 087-crandash
- 088-action-pattern1
- 089-action-pattern2
- 090-action-pattern3
- 091-action-pattern4
- 092-action-pattern5
- 093-plot-interaction-basic
- 094-image-interaction-basic
- 095-plot-interaction-advanced
- 096-plot-interaction-article-1
- 097-plot-interaction-article-2
- 098-plot-interaction-article-3
- 099-plot-interaction-article-4
- 100-plot-interaction-article-5
- 101-plot-interaction-article-6
- 102-plot-interaction-article-7
- 103-plot-interaction-article-8
- 104-plot-interaction-select
- 105-plot-interaction-zoom
- 106-plot-interaction-exclude
- 107-events
- 108-module-output
- 109-render-table
- 110-error-sanitization
- 111-insert-ui
- 112-generate-report
- 113-bookmarking-url
- 114-modal-dialog
- 115-bookmarking-updatequerystring
- 116-notifications
- 117-shinythemes
- 118-highcharter-births

</details>

**Comment by daattali** [comment]
I was excited to get a look into the shiny dev center! But that link is not publicly available...

rstudio/shiny-dev-center#38

**Comment by dmpe** [comment]
And could you please tell us what are the  last two (119+120) test cases and their links? in the https://github.com/rstudio/shiny-examples they do not exist.

>Winston: any browser; gallery.shinyapps.io; 080-120

thanks.

**Comment by bborgesr** [comment]
@daattali: Right, sorry, it's a private repo, it was just a note for ourselves. It's also misplaced there because it referred to the 1.0.1 release and I just copied it over from https://github.com/rstudio/shiny/issues/1622. All those changes are now in the website. There are no relevant changes to shiny-dev-center for this release (we'll just update the version number). The change from 1.0.1 were:

- a new article about usage tracking: http://shiny.rstudio.com/articles/usage-metrics.html
- the upgrade notes article: http://shiny.rstudio.com/articles/upgrade-1.0.1.html
- a code correction/update on this article: http://shiny.rstudio.com/articles/pool-dplyr.html
- add info about new fields in shiny:inputchanged JS event, and new shiny:filedownload event: http://shiny.rstudio.com/articles/js-events.html
- add translation of submitButton code to actionButton code: http://shiny.rstudio.com/articles/action-buttons.html
- a slight rewriting of http://shiny.rstudio.com/articles/dynamic-ui.html

----

@dmpe There's no example 119 and 120. That was just the rough division by three that we did. There's a few other numbers that don't correspond to apps (e.g. 31, 58)...

**Comment by dmpe** [comment]
PS: it it makes testing any easier feel free to use mine table https://bs40.tk/WorksOrNotTable/
