### ISSUE TITLE
Shiny 1.0.4 release checklist

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#1806]
## Code completion
- [x] Merge dynamic tabs into master
- [x] Merge drag and drop fileInputs to master

## Shiny
- [x] Final test pass 
     - [x] **Alan**: IE 9 - Shiny Server Pro
     - [x] **Alan**: IE 11 - ShinyApps.io
     - [x] **Winston**: Firefox - RSConnect
     - [x] **Winston**: Chrome - Shiny Server
     - [x] **Barbara**: Edge - ShinyApps.io
     - [x] **Barbara**: Safari - Shiny Server Pro 
- [x] NEWS is up to date
- [x] LICENSE is up to date
- [x] Version bump
- [x] Run Grunt (so that shiny.js.min gets updated version number)
- [x] R CMD check --as-cran
- [x] Reverse dependency check
- [ ] Email shiny-discuss
- [x] Submit to CRAN
- [x] When accepted on CRAN, tag commit with version, push tag
- [x] Draft blog post
- [x] Publish blog post

## shiny.rstudio.com
- [x] Make sure all articles are added in master
- [x] Run staticdocs
- [x] Move previous /reference/latest to /reference/vX.Y.Z
- [x] Upgrade notes
- [x] Merge into master: https://github.com/rstudio/shiny-dev-center/pull/66
- [x] Redeploy gallery.shinyapps.io

**Comment by dmenne** [comment]
I wanted to try the drag and drop feature - is there a branch with it, and some documentation (even preliminary)?

**Comment by wch** [comment]
@dmenne It's not merged yet; it's in pull request #1782. There are a few issues we still need to iron out, but you can try it with `devtools::install_github("rstudio/shiny@alandipert/fileInput-drag-drop")`.

**Comment by dmenne** [comment]
Thanks, works for me. Are you sure "span" is a good idea? If I use it in the narrow left bar, an optional break between button and Drag-field, or even Field-top, would be nice. I have not tried too many CSS-options yet.

**Comment by bborgesr** [comment]
I'm creating this for myself, but feel free to use it/copy it for your own testing. The idea is to check every app that runs fine in all of my test permutations (which for this release is just 2 per app) and put notes next to the ones that don't work (helpful for the next release since there are browser compatibility issues that endure)...

- [ ] 001-hello
- [ ] 002-text
- [ ] 003-reactivity
- [ ] 004-mpg
- [ ] 005-sliders
- [ ] 006-tabsets
- [ ] 007-widgets
- [ ] 008-html
- [ ] 009-upload
- [ ] 010-download
- [ ] 011-timer
- [ ] 012-datatables
- [ ] 013-selectize
- [ ] 014-onflushed
- [ ] 015-layout-navbar
- [ ] 015-layout-sidebar
- [ ] 016-knitr-pdf
- [ ] 017-select-vs-selectize
- [ ] 018-datatable-options
- [ ] 019-mathjax
- [ ] 020-knit-html
- [ ] 021-selectize-plot
- [ ] 022-unicode-chinese
- [ ] 023-optgroup-server
- [ ] 024-optgroup-selectize
- [ ] 025-loop-ui
- [ ] 026-shiny-inline
- [ ] 027-absolutely-positioned-panels
- [ ] 028-actionbutton-demo
- [ ] 030-basic-datatable
- [ ] 032-client-data-and-query-string
- [ ] 033-conditionalpanel-demo
- [ ] 034-current-time
- [ ] 035-custom-input-bindings
- [ ] 036-custom-input-control
- [ ] 037-date-and-date-range
- [ ] 039-download-file
- [ ] 040-dynamic-clustering
- [ ] 041-dynamic-ui
- [ ] 047-image-output
- [ ] 048-including-html-text-and-markdown-files
- [ ] 049-isolate-demo
- [ ] 050-kmeans-example
- [ ] 051-movie-explorer
- [ ] 052-navbar-example
- [ ] 053-navlistpanel-example
- [ ] 054-nvd3-line-chart-output
- [ ] 055-observer-demo
- [ ] 057-plot-plus-three-columns
- [ ] 059-reactive-poll-and-file-reader
- [ ] 060-retirement-simulation
- [ ] 061-server-to-client-custom-messages
- [ ] 062-submitbutton-demo
- [ ] 063-superzip-example
- [ ] 064-telephones-by-region
- [ ] 065-update-input-demo
- [ ] 066-upload-file
- [ ] 067-vertical-layout
- [ ] 068-widget-action-button
- [ ] 069-widget-check-group
- [ ] 070-widget-checkbox
- [ ] 071-widget-date
- [ ] 072-widget-date-range
- [ ] 073-widget-file
- [ ] 074-widget-numeric
- [ ] 075-widget-radio
- [ ] 076-widget-select
- [ ] 077-widget-slider
- [ ] 078-widget-slider-range
- [ ] 079-widget-submit
- [ ] 080-widget-text
- [ ] 081-widgets-gallery
- [ ] 082-word-cloud
- [ ] 083-front-page
- [ ] 084-single-file
- [ ] 085-progress
- [ ] 086-bus-dashboard
- [ ] 087-crandash
- [ ] 088-action-pattern1
- [ ] 089-action-pattern2
- [ ] 090-action-pattern3
- [ ] 091-action-pattern4
- [ ] 092-action-pattern5
- [ ] 093-plot-interaction-basic
- [ ] 094-image-interaction-basic
- [ ] 095-plot-interaction-advanced
- [ ] 096-plot-interaction-article-1
- [ ] 097-plot-interaction-article-2
- [ ] 098-plot-interaction-article-3
- [ ] 099-plot-interaction-article-4
- [ ] 100-plot-interaction-article-5
- [ ] 101-plot-interaction-article-6
- [ ] 102-plot-interaction-article-7
- [ ] 103-plot-interaction-article-8
- [ ] 104-plot-interaction-select
- [ ] 105-plot-interaction-zoom=
- [ ] 106-plot-interaction-exclude
- [ ] 107-events
- [ ] 108-module-output
- [ ] 109-render-table
- [ ] 110-error-sanitization
- [ ] 111-insert-ui
- [ ] 112-generate-report
- [ ] 113-bookmarking-url
- [ ] 114-modal-dialog
- [ ] 115-bookmarking-updatequerystring
- [ ] 116-notifications
- [ ] 117-shinythemes
- [ ] 118-highcharter-births
