### ISSUE TITLE
Shiny 1.1 release checklist

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#2002]
## Shiny
- [x] Final test pass 
- [x] Run Grunt (so that shiny.js.min gets updated version number)
- [x] NEWS is up to date
- [x] LICENSE is up to date
- [x] Version bump
- [x] R CMD check --as-cran
- [x] Reverse dependency check
- [x] Submit to CRAN
- [x] When accepted on CRAN, tag commit with version, push tag
- [x] Draft blog post
- [x] Publish blog post
- [ ] Community post
- [x] Announcement tweet

## shiny.rstudio.com
- [x] Make sure all articles are added in PR https://github.com/rstudio/shiny-dev-center/pull/102
  - [x] async
- [x] Run staticdocs
- [x] Move previous /reference/latest to /reference/vX.Y.Z
- [x] Upgrade notes
- [x] Merge pending changes for Shiny 1.1 into master (PR @ https://github.com/rstudio/shiny-dev-center/pull/102)
- [ ] Redeploy gallery.shinyapps.io
