### ISSUE TITLE
Shiny 1.2 release checklist

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#2190]
## Shiny
- [x] Create RC branch `v1.2-rc`
- [x] Version bump
- [x] Run Grunt (so that shiny.js.min gets updated version number)
- [x] NEWS is up to date
- [x] LICENSE is up to date
- [x] Final test pass 
- [x] All milestone issues/PRs closed https://github.com/rstudio/shiny/milestone/8
- [x] R CMD check --as-cran
- [x] R CMD check --as-cran from command line
- [x] Reverse dependency check
- [x] Submit to CRAN
- [x] When accepted on CRAN, tag commit with version, push tag
- [x] Draft blog post https://github.com/rstudio/blog/pull/132
- [x] Publish blog post
- [x] Community post
- [x] Announcement tweet

## shiny.rstudio.com
- [x] Make sure all articles are added in PR https://github.com/rstudio/shiny-dev-center/pull/104
- [x] Run staticdocs
- [x] Move previous /reference/latest to /reference/vX.Y.Z
- [x] Upgrade notes
- [x] Merge pending changes for Shiny 1.1 into master https://github.com/rstudio/shiny-dev-center/pull/104
- [x] Redeploy gallery.shinyapps.io

**Comment by cpsievert** [comment]
Some issues I found during testing:

* Undesirable behavior when searching for states in [021-selectize-plot](https://github.com/rstudio/shiny-examples/tree/master/021-selectize-plot)

![021](https://user-images.githubusercontent.com/1365941/46027753-37f13100-c0b4-11e8-8364-5f06941bd926.gif)

* [023-optgroup-server](https://github.com/rstudio/shiny-examples/tree/master/023-optgroup-server)

![023](https://user-images.githubusercontent.com/1365941/46028057-31af8480-c0b5-11e8-9a1e-78e31e6f8920.gif)
