### ISSUE TITLE
Shiny 1.3 release checklist

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#2337]
## Shiny
- [x] Create RC branch `v1.3.0-rc`
- [x] Version bump
- [x] Run Grunt (so that shiny.js.min gets updated version number)
- [x] NEWS is up to date
- [x] LICENSE is up to date
- [x] Final test pass 
- [x] All milestone issues/PRs closed
- [x] R CMD check --as-cran
- [x] R CMD check --as-cran from command line
- [x] Reverse dependency check
- [x] httpuv accepted to CRAN
- [x] reactlog accepted to CRAN
- [x] Submit to CRAN
- [x] When accepted on CRAN, tag commit with version, push tag
- [x] Draft blog post https://github.com/rstudio/blog/pull/132
- [ ] Publish blog post
- [ ] Community post
- [ ] Announcement tweet

## shiny.rstudio.com
- [ ] Make sure all articles are added to PR
- [ ] Run staticdocs
- [ ] Move previous /reference/latest to /reference/vX.Y.Z
- [ ] Upgrade notes
- [ ] Merge pending changes for Shiny 1.3 into master
- [ ] Redeploy gallery.shinyapps.io
