### ISSUE TITLE
Shiny 1.3.1 release checklist

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#2379]
## Shiny
- [x] Create RC branch `rc-v1.3.1`
- [x] Version bump
- [x] Run Grunt (so that shiny.js.min gets updated version number)
- [x] NEWS is up to date
- [x] LICENSE is up to date
- [ ] Final test pass 
- [ ] All milestone issues/PRs closed
- [ ] R CMD check --as-cran
- [ ] R CMD check --as-cran from command line
- [ ] Reverse dependency check
- [ ] httpuv accepted to CRAN
- [ ] reactlog accepted to CRAN
- [ ] Submit to CRAN
- [ ] When accepted on CRAN, tag commit with version, push tag
- [ ] Draft blog post https://github.com/rstudio/blog/pull/132
- [ ] Publish blog post
- [ ] Community post
- [ ] Announcement tweet

## shiny.rstudio.com
- [ ] Make sure all articles are added to PR
- [ ] Run staticdocs
- [ ] Move previous /reference/latest to /reference/vX.Y.Z
- [ ] Upgrade notes
- [ ] Merge pending changes for Shiny 1.3.1 into master
- [ ] Redeploy gallery.shinyapps.io

**Comment by jcheng5** [comment]
Note: I didn't actually run grunt, because of changes that were inadvertently not grunted into Shiny 1.3.0 that we want to continue to not grunt into Shiny 1.3.1. Instead, I manually changed the version numbers (one in shiny.js, two in shiny.min.js) and used byte-for-byte comparison to verify that only the intended characters were changed.

```
diff -U2 <(xxd <(git show HEAD^:inst/www/shared/shiny.min.js)) <(xxd <(git show HEAD:inst/www/shared/shiny.min.js))
```

**Comment by alandipert** [comment]
Closing because Shiny 1.3.1 and then Shiny 1.3.2 went out, and all of these things were done.
