### ISSUE TITLE
Shiny 1.4.0 release checklist

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#2649]
## Shiny
- [x] Create RC branch `rc-v1.4.0`
- [x] Version bump
- [x] Run Grunt (so that shiny.js.min gets updated version number)
- [x] NEWS is up to date
- [x] LICENSE is up to date
- [x] Final test pass 
- [x] All milestone issues/PRs closed
- [x] R CMD check --as-cran
- [x] R CMD check --as-cran from command line
- [x] Reverse dependency check
- [x] Submit to CRAN
- [x] When accepted on CRAN, tag commit with version, push tag
- [x] Draft blog post
- [ ] Publish blog post
- [ ] Community post
- [ ] Announcement tweet

## shiny.rstudio.com
- [x] Make sure all articles are added to PR
- [x] Run staticdocs
- [x] Move previous /reference/latest to /reference/vX.Y.Z
- [x] Upgrade notes
- [x] Merge pending changes for Shiny 1.4.0 into master
- [ ] Redeploy gallery.shinyapps.io
