### ISSUE TITLE
Outstanding issues for migration to jsonlite

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#767]
The development version of Shiny has switched from RJSONIO to jsonlite, but there are some remaining differences in behavior that should be addressed before a release.

* [x] `toJSON(auto_unbox=TRUE)` can generate invalid JSON: jeroenooms/jsonlite#71. (Workaround already in Shiny)
* [x] `toJSON` drops names of named vectors:  jeroenooms/jsonlite#76
* [x] `toJSON` for objects wrapped with `I()` differs from RJSONIO's behavior: https://github.com/timelyportfolio/parcoords/issues/6#issuecomment-81215063. For this one it's not clear to me that we should try to mimic RJSONIO's behavior.
